# This is a basic workflow to help you get started with Actions

name: Deploy via WebDAV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install Curl
      - name: Install Curl
        run: sudo apt-get install curl

      # Upload the files via WebDAV into the correct theme in resources/Theme_Overrides directory
      - name: Upload files via WebDAV
        env:
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: LOCAL_SOURCE="dist"
          WEBDAV_TARGET="whiteboard_maya_blue.v3.0"
          find $DIRECTORY -type f | while read FILE; do
          echo "Uploading $FILE to $WEBDAV_URL/$WEBDAV_TARGET/$(basename "$FILE")"
          curl --user "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" -T "$FILE" "$WEBDAV_URL/$WEBDAV_TARGET/$(basename "$FILE")"
          done
